linters-settings:
  goimports:
    local-prefixes: github.com/danielnetop/notesnook-to-standardnotes
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: true
  funlen:
    lines: 80
    statements: 40
  gocognit:
    min-complexity: 15
  nestif:
    min-complexity: 4
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 15
  godot:
    capital: true
  gofmt:
    simplify: true
  govet:
    check-shadowing: false
  lll:
    line-length: 120
    tab-width: 1
  misspell:
    locale: US
  nakedret:
    max-func-lines: 20
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
  whitespace:
    multi-if: false
    multi-func: false
  wsl:
    allow-assign-and-call: true
    force-err-cuddling: true
  gofumpt:
    lang-version: "1.18"
    extra-rules: false

linters:
  # Enable extra linters besides the default ones
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
    - unused

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - lll
        - funlen
